version: "3.9"
services:
  cms:
    build:
      context: .
      dockerfile: ./Dockerfile
    container_name: cms
    env_file:
      - ./.env
    environment:
      - VIRTUAL_HOST
    ports:
      - 8000:80

  swag:
    image: lscr.io/linuxserver/swag:latest
    container_name: swag
    depends_on:
      - cms
    environment:
      - VIRTUAL_HOST
      - VIRTUAL_PORT=8000
    ports:
      - 443:443
      - 80:80
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
